#!/bin/bash

# e: Exit when first line is an error:
# x: Echo info per command
set -e

# hooks/build
# https://docs.docker.com/docker-cloud/builds/advanced/

# $IMAGE_NAME var is injected into the build so the tag is correct.
echo "[***] Build hook running"

GIT_COMMIT=$(git rev-parse HEAD)
GIT_SHA=${GIT_COMMIT:0:12}
GIT_DESC=$(git describe --tags --always)
GIT_URL=$(git config --get remote.origin.url)
GIT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
CUR_TIME=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

echo "GIT_COMMIT: $GIT_COMMIT"
echo "GIT_SHA: $GIT_SHA"
echo "GIT_DESC: $GIT_DESC"
echo "GIT_URL: $GIT_URL"
echo "GIT_BRANCH: $GIT_BRANCH"
echo "CUR_TIME: $CUR_TIME"

set -ex

docker build \
  --build-arg GIT_COMMIT="$GIT_COMMIT" \
  --build-arg GIT_SHA="$GIT_SHA" \
  --build-arg GIT_DESC="$GIT_DESC" \
  --build-arg GIT_URL="$GIT_URL" \
  --build-arg GIT_BRANCH="$GIT_BRANCH" \
  --build-arg GIT_TIME="$GIT_TIME" \  
  -t $IMAGE_NAME .