#!/bin/bash

# e: Exit when first line is an error: x: Echo info per command
set -e

echo "IMAGE_NAME: $IMAGE_NAME"
echo "DOCKER_REPO: $DOCKER_REPO"
echo "DOCKERFILE_PATH: $DOCKERFILE_PATH"

set -ex

# Tag the latest build with the short git sha. Push the tag in addition to the "latest" tag already pushed.
docker build -f $DOCKERFILE_PATH -t $IMAGE_NAME .
