#!/bin/bash

# e: Exit when first line is an error: x: Echo info per command
set -e

echo "IMAGE_NAME: $IMAGE_NAME"
echo "DOCKER_REPO: $DOCKER_REPO"
echo "DOCKERFILE_PATH: $DOCKERFILE_PATH"
echo "SOURCE_COMMIT: $SOURCE_COMMIT"
echo "DOCKERFILE_PATH : $DOCKERFILE_PATH"

set -ex

# Tag the latest build with the short git sha. Push the tag in addition to the "latest" tag already pushed.
GIT_SHA_TAG=${SOURCE_COMMIT:0:12}
docker tag $IMAGE_NAME $DOCKER_REPO:$GIT_SHA_TAG
docker push $DOCKER_REPO:$GIT_SHA_TAG

echo "Build with notebooks and push"
docker build --build-arg BASE_CONTAINER=$IMAGE_NAME -f Dockerfile -t $DOCKER_REPO:notebooks ../
docker push $DOCKER_REPO:notebooks